from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from datetime import datetime


def generate_report(path, user, dataset, stats):

    doc = SimpleDocTemplate(path, pagesize=A4)
    elements = []

    styles = getSampleStyleSheet()
    title_style = styles["Heading1"]
    normal_style = styles["Normal"]

    # ================= TITLE =================
    elements.append(Paragraph("Fraud Detection Audit Report", title_style))
    elements.append(Spacer(1, 0.3 * inch))

    # ================= REPORT META =================
    elements.append(Paragraph(f"Generated on: {datetime.utcnow()}", normal_style))
    elements.append(Spacer(1, 0.2 * inch))

    # ================= USER INFORMATION =================
    elements.append(Paragraph("<b>User Information</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    user_data = [
        ["Name", user.name],
        ["Email", user.email],
        ["User ID", user.id]
    ]

    user_table = Table(user_data, colWidths=[2 * inch, 4 * inch])
    user_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey)
    ]))

    elements.append(user_table)
    elements.append(Spacer(1, 0.4 * inch))

    # ================= DATASET INFORMATION =================
    elements.append(Paragraph("<b>Dataset Information</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    dataset_data = [
        ["Filename", dataset.filename],
        ["Rows", dataset.num_rows],
        ["Columns", dataset.num_columns],
        ["Model Path", dataset.model_path],
        ["Uploaded At", str(dataset.uploaded_at)],
        ["Dataset ID", dataset.id]
    ]

    dataset_table = Table(dataset_data, colWidths=[2 * inch, 4 * inch])
    dataset_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey)
    ]))

    elements.append(dataset_table)
    elements.append(Spacer(1, 0.4 * inch))

    # ================= FRAUD ANALYSIS SUMMARY =================
    elements.append(Paragraph("<b>Fraud Analysis Summary</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    fraud_rate = 0
    if stats["total"] > 0:
        fraud_rate = round((stats["fraud"] / stats["total"]) * 100, 2)

    summary_data = [
        ["Total Transactions", stats["total"]],
        ["High Risk Transactions", stats["fraud"]],
        ["Medium Risk Transactions", stats.get("medium", 0)],
        ["Low Risk Transactions", stats.get("low", 0)],
        ["Fraud Rate (%)", f"{fraud_rate}%"]
    ]

    summary_table = Table(summary_data, colWidths=[2.5 * inch, 3.5 * inch])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey)
    ]))

    elements.append(summary_table)
    elements.append(Spacer(1, 0.4 * inch))

    # ================= RISK INTERPRETATION =================
    elements.append(Paragraph("<b>Risk Interpretation</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    if fraud_rate > 5:
        interpretation = "Elevated fraud activity detected. Immediate investigation is recommended."
    else:
        interpretation = "Fraud activity within acceptable operational limits."

    elements.append(Paragraph(interpretation, normal_style))
    elements.append(Spacer(1, 0.4 * inch))

    # ================= SYSTEM DISCLAIMER =================
    elements.append(Paragraph("<b>System Integrity Statement</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    disclaimer_text = """
    This report was automatically generated by the Fraud Detection System.
    All predictions are based on the trained machine learning model associated
    with the uploaded dataset. The results should be reviewed by compliance
    officers before any operational decision is made.
    """

    elements.append(Paragraph(disclaimer_text, normal_style))

    # Build PDF
    doc.build(elements)

